server:
  port: 8081

#???? ?? ??
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      #default? circuit open? 10??? 20? ?? 50%?? ???? ??? ????.
      circuitBreaker:
        requestVolumeThreshold: 1 #circuit breaker? ??? ?????? ?? ???.
        errorThresholdPercentage: 50 #?? ?? ?? default 50
